name: ai_news_summarizer
description: A Flutter project for summarizing news articles using AI.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.5
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  google_generative_ai:  0.2.2
  image_picker: 1.0.7
  flutter_dotenv: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
